version: '3'

services:
  localstack:
    image: localstack/localstack-pro:3
    stop_grace_period: 1m
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - AWS_DEFAULT_REGION=eu-central-1
      - DEBUG=0
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock